apiVersion: v1
data:
  openlineage.yml: |-
    transport:
      type: http
      url: http://marquez.marquez.svc.cluster.local:5000
      endpoint: /api/v1/lineage
      timeoutInMillis: 5000
kind: ConfigMap
metadata:
  name: silver-m3-product-inventory-openlineage-config
  namespace: flink-kubernetes-operator
