apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: marquez
  namespace: argocd
spec:
  destination:
    namespace: marquez
    server: https://kubernetes.default.svc
  project: default
  sources:
  - helm:
      valueFiles:
      - $values/gitops/manifests/marquez/values.yaml
    path: chart
    repoURL: https://github.com/MarquezProject/marquez.git
    targetRevision: main
  - directory:
      recurse: true
    path: gitops/manifests/marquez
    ref: values
    repoURL: git@github.com:bytetum/k8s-dataplatform-quickstart.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - CreateNamespace=true
