apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: schema-registry-credentials
  namespace: flink-kubernetes-operator
spec:
  dataFrom:
  - extract:
      key: id:schema-registry-credentials
      version: latest_enabled
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    creationPolicy: Owner
    name: schema-registry-credentials
