apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flink-bucket-credentials
  namespace: flink-kubernetes-operator
spec:
  dataFrom:
  - extract:
      key: id:flink-s3-credentials-secret
      version: latest_enabled
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    creationPolicy: Owner
    name: flink-bucket-credentials
