apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flink-sql-gateway-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flink-sql-gateway-role
subjects:
- kind: ServiceAccount
  name: flink-sql-gateway-sa
  namespace: flink-kubernetes-operator
