apiVersion: v1
data:
  flink-conf.yaml: |-
    jobmanager.rpc.address: flink-jobmanager
    rest.address: flink-jobmanager
    taskmanager.numberOfTaskSlots: 2
    blob.server.port: 6124
    jobmanager.rpc.port: 6123
    taskmanager.rpc.port: 6122
    jobmanager.memory.process.size: 1024m
    taskmanager.memory.process.size: 2048m
    parallelism.default: 2

    execution.checkpointing.interval: 1min
    execution.checkpointing.storage: filesystem
    execution.checkpointing.dir: s3://local-rocksdb-test/flink-session-mode/checkpoints

    state.backend.type: rocksdb
    execution.checkpointing.incremental: true
    execution.checkpointing.savepoint-dir: s3://local-rocksdb-test/flink-session-mode/savepoints
    state.backend.rocksdb.localdir: /data/rocksdb
    jobmanager.archive.fs.dir: s3://local-rocksdb-test/flink-session-mode/completed-jobs
    high-availability.storageDir: s3://local-rocksdb-test/flink-session-mode/ha
    kubernetes.cluster-id: flink-session-cluster-01
    high-availability.type: kubernetes

    # Prometheus metrics reporter
    metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
  log4j-console.properties: |-
    rootLogger.level = INFO
    rootLogger.appenderRef.console.ref = ConsoleAppender
    rootLogger.appenderRef.rolling.ref = RollingFileAppender
    logger.pekko.name = org.apache.pekko
    logger.pekko.level = INFO
    logger.kafka.name= org.apache.kafka
    logger.kafka.level = INFO
    logger.hadoop.name = org.apache.hadoop
    logger.hadoop.level = INFO
    logger.zookeeper.name = org.apache.zookeeper
    logger.zookeeper.level = INFO
    appender.console.name = ConsoleAppender
    appender.console.type = CONSOLE
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
    appender.rolling.name = RollingFileAppender
    appender.rolling.type = RollingFile
    appender.rolling.append = false
    appender.rolling.fileName = ${sys:log.file}
    appender.rolling.filePattern = ${sys:log.file}.%i
    appender.rolling.layout.type = PatternLayout
    appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
    appender.rolling.policies.type = Policies
    appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
    appender.rolling.policies.size.size=100MB
    appender.rolling.strategy.type = DefaultRolloverStrategy
    appender.rolling.strategy.max = 10
    logger.netty.name = org.jboss.netty.channel.DefaultChannelPipeline
    logger.netty.level = OFF
kind: ConfigMap
metadata:
  labels:
    app: flink
  name: flink-config
  namespace: flink-kubernetes-operator
