apiVersion: v1
kind: Service
metadata:
  name: flink-sql-gateway-service
  namespace: flink-kubernetes-operator
spec:
  ports:
  - name: rest
    port: 8083
    targetPort: 8083
  selector:
    app: flink
    component: sql-gateway
  type: ClusterIP
