---
# Source: marquez/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: marquez-postgresql
  namespace: "marquez"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-11.8.1
    app.kubernetes.io/instance: marquez
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgres-password: "VjRnZ0RXN0thbQ=="
  password: "bWFycXVleg=="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
