---
# Source: marquez/templates/marquez/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: marquez-config
  labels:
    app.kubernetes.io/name: marquez
    helm.sh/chart: marquez-0.51.1
    app.kubernetes.io/instance: marquez
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: marquez
  annotations:
data:
  ### HTTP SERVER CONFIG ###

  config.yml: |-
    # Enables HTTP server configuration overrides (see: https://www.dropwizard.io/en/stable/manual/configuration.html#servers)
    server:
      applicationConnectors:
      - type: http
        port: ${MARQUEZ_PORT}
        httpCompliance: RFC7230_LEGACY
      adminConnectors:
      - type: http
        port: ${MARQUEZ_ADMIN_PORT}

    ### DATABASE CONFIG ###

    # Enables database configuration overrides (see: https://www.dropwizard.io/en/stable/manual/configuration.html#database)
    db:
      driverClass: org.postgresql.Driver
      url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
    # Enables retention policy configuration for database (default: disabled)
    dbRetention:
      frequencyMins: 15
      numberOfRowsPerBatch: 1000
      retentionDays: 7

    # Enables database migration on startup (default: true)
    migrateOnStartup: ${MIGRATE_ON_STARTUP}
    logging:
      level: ${LOG_LEVEL}
      appenders:
        - type: console
