---
# Source: marquez/templates/marquez/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marquez
  labels:
    app.kubernetes.io/name: marquez
    helm.sh/chart: marquez-0.51.1
    app.kubernetes.io/instance: marquez
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: marquez
  annotations:
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: marquez
      app.kubernetes.io/instance: marquez
      app.kubernetes.io/component: marquez
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: marquez
        helm.sh/chart: marquez-0.51.1
        app.kubernetes.io/instance: marquez
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: marquez
    spec:
      serviceAccountName: default
      # This init container is for avoiding CrashLoopback errors in the Marquez container because the PostgreSQL container is not ready
      initContainers:
        - name: wait-for-db
          image: docker.io/bitnami/postgresql:14.15.0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
          args:
            - -ec
            - until pg_isready -h ${POSTGRES_HOST} -p ${POSTGRES_PORT} -U ${POSTGRES_USER}; do echo waiting for database; sleep 2; done;
          env:
            - name: POSTGRES_HOST
              value: "marquez-postgresql"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "marquez"
      containers:
        - name: marquez
          image: docker.io/marquezproject/marquez:0.51.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: marquez-volume
              mountPath: /usr/src/app/config.yml
              subPath: config.yml
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
            - name: http-admin
              containerPort: 5001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http-admin
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http-admin
          env:
            - name: MARQUEZ_PORT
              value: "5000"
            - name: MARQUEZ_ADMIN_PORT
              value: "5001"
            - name: MARQUEZ_CONFIG
              value: /usr/src/app/config.yml
            - name: POSTGRES_HOST
              value: "marquez-postgresql"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "marquez"
            - name: POSTGRES_USER
              value: "marquez"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: marquez-postgresql
                  key: password
            - name: MIGRATE_ON_STARTUP
              value: "true"
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
      volumes:
        - name: marquez-volume
          configMap:
            name: marquez-config
