---
# Source: marquez/templates/marquez/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: marquez
  labels:
    app.kubernetes.io/name: marquez
    helm.sh/chart: marquez-0.51.1
    app.kubernetes.io/instance: marquez
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  marquez-db-password: "bWFjb25kbw=="
