---
# Source: marquez/templates/web/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marquez-web
  labels:
    app.kubernetes.io/name: marquez
    helm.sh/chart: marquez-0.51.1
    app.kubernetes.io/instance: marquez
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: marquez
      app.kubernetes.io/instance: marquez
      app.kubernetes.io/component: web
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: marquez
        helm.sh/chart: marquez-0.51.1
        app.kubernetes.io/instance: marquez
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: marquez-web
          image: docker.io/marquezproject/marquez-web:0.51.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
          env:
            - name: MARQUEZ_HOST
              value: marquez
            - name: MARQUEZ_PORT
              value: "80"
            - name: WEB_PORT
              value: "3000"
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
