marquez:
  port: 5000
  adminPort: 5001
  migrateOnStartup: true
  db:
    host: marquez-postgres
    port: 5432
    name: marquez
    user: marquez
    password: marquez
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

web:
  enabled: true
  port: 3000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

postgresql:
  enabled: false
