apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: openmetadata
type: Opaque
stringData:
  openmetadata-mysql-password: openmetadata_password
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: openmetadata
type: Opaque
stringData:
  openmetadata-airflow-password: admin
